---
- name: "PLAY 1 - ISSUE SNMP COMMANDS"
  hosts: "iosxe"
  gather_facts: "no"
  connection: "ansible.netcommon.network_cli"

  tasks:
    - name: "TASK1 - SHOW SNMP CONFIG"
      ios_commands:
        commands:
          - "show run | in snmp"

    - name: "TASK2 - DEPLOY SNMP COMMANDS"
      cisco.ios.ios_config:
        commands:
          - "snmp-server chassid-id {{ inventory_hostname }}"
