---
- name: "TASK 1 - SHOW SNMP CONFIG"
  hosts: iosxe
  connection: "ansible.netcommon.network_cli"
  gather_facts: no

  tasks:
    - name: "ISSUE SHOW COMMAND"
      cisco.ios.ios_command:
        commands:
          - "show run | in snmp-server community"
        register: snmp_data

    - name: "DEBUG COMMAND STRING RESPONSE WITH JINJA SHORTHAND SYNTAX"
      debug:
        var: snmp_data.stdout.0

    - name: "DEBUG COMMAND STRING RESPONSE WITH STANDARD PYTHON SYNTAX"
      debug:
        var: snmp_data['stdout'][0]

    - name: "WRITE DATA TO FILE"
      template:
        src: "basic.j2"
        dest: "./commands/snmp/{{ inventory_hostname }}.txt"
